#!/usr/bin/python
# Copyright (C) 2012 Allis Tauri <allista@gmail.com>
# 
# degen_primer is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# indicator_gddccontrol is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
Created on Jul 29, 2012

@author: Allis Tauri <allista@gmail.com>
'''


import sys
import signal
from PyQt4.QtCore import QTimer
from PyQt4.QtGui import QApplication
from DegenPrimerGUI.DegenPrimerGUI import DegenPrimerGUI

def sig_handler(signal, frame):
    QApplication.closeAllWindows()

if __name__ == '__main__':
    #setup signal handler
    signal.signal(signal.SIGINT,  sig_handler)
    signal.signal(signal.SIGTERM, sig_handler)
    signal.signal(signal.SIGQUIT, sig_handler)
    #setup main application
    app = QApplication(sys.argv)
    #let python interpreter run each 500ms to catch a signal
    timer = QTimer()
    timer.start(500)
    timer.timeout.connect(lambda: None)
    #setup main window
    degen_primer_main = DegenPrimerGUI()
    #catch stdout/err
    sys.stdout = degen_primer_main
    sys.stderr = degen_primer_main
    #show main window
    degen_primer_main.show()
    #run
    sys.exit(app.exec_())