#!/usr/bin/python
# Copyright (C) 2012 Allis Tauri <allista@gmail.com>
# 
# degen_primer is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# degen_primer_gui is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
Created on Jul 29, 2012

@author: Allis Tauri <allista@gmail.com>
'''


import sys, os
import signal
import argparse
from time import sleep
from PyQt4.QtCore import QTimer
from PyQt4.QtGui import QApplication
from DegenPrimerGUI.DegenPrimerGUI import DegenPrimerGUI


_pid = -1
def sig_handler(signal, frame):
    if _pid != os.getpid(): return
    QApplication.closeAllWindows()
    sleep(1)
    sys.exit(1)
#end def
   

if __name__ == '__main__':
    #set PID
    _pid = os.getpid()
    #setup signal handler
    signal.signal(signal.SIGINT,  sig_handler)
    signal.signal(signal.SIGTERM, sig_handler)
    signal.signal(signal.SIGQUIT, sig_handler)
    #parse command-line arguments
    parser = argparse.ArgumentParser('GUI for DegenPrimer')
    conf_group = parser.add_argument_group('Preset configuration')
    conf_group.add_argument('config_file', metavar='file.cfg', 
                            type=str, nargs='?',
                            help='Path to the analysis configuration file.')
    args = parser.parse_args()
    config_file = args.config_file
    #setup main application
    app = QApplication(sys.argv)
    QApplication.setOrganizationName('DegenPrimer')
    QApplication.setApplicationName('DegenPrimerGUI')
    #let python interpreter run each 500ms to catch a signal
    timer = QTimer()
    timer.start(500)
    timer.timeout.connect(lambda: None)
    #setup main window
    degen_primer_main = DegenPrimerGUI()
    #catch stdout/err
    sys.stdout = degen_primer_main
    sys.stderr = degen_primer_main
    #show main window
    degen_primer_main.show()
    #if configuration file is provided, parse it
    if config_file:
        degen_primer_main.load_config(config_file)
    #run
    sys.exit(app.exec_())