#!/usr/bin/python
# Copyright (C) 2012 Allis Tauri <allista@gmail.com>
# 
# degen_primer is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# indicator_gddccontrol is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
Created on Jul 29, 2012

@author: Allis Tauri <allista@gmail.com>
'''


import sys
from PyQt4.QtGui import QApplication
from DegenPrimerGUI.DegenPrimerGUI import DegenPrimerGUI

if __name__ == '__main__':
    app = QApplication(sys.argv)
    degen_primer_main = DegenPrimerGUI()
    #catch stdout/err
    sys.stdout = degen_primer_main
    sys.stderr = degen_primer_main
    degen_primer_main.show()
    sys.exit(app.exec_())